### ISSUE TITLE
Extraction and Symlinks

### ISSUE THREAD

**Issue by jamiethalacker** [innatical/apkg#1]
if we have a symlink in a package, let's say `binutils.apkg` (binutils.apkg has /usr/bin/ld -> /usr/bin/ld.bfd), apkg fails to extract it, and creates $ROOT/packages/582093475049328750934857/usr/bin/ld as a blank text file, instead of properly symlinking it to `ld.bfd`.
**TOP**: apkg extracted into packages folder. Notice how `ld` is a blank file
**BOTTOM**: `tar -xvf binutils.apkg`. Notice how `ld` is an actual application
![image](https://user-images.githubusercontent.com/22264706/139557516-fffbfce5-b205-4100-817e-1ca32ff9eacf.png)

**Comment by lleyton** [comment]
Fixed
